# Generated by Django 4.0.4 on 2022-09-04 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0004_reserva_total_gasto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='total_gasto',
            new_name='total',
        ),
    ]
