# Generated by Django 4.0.4 on 2022-11-03 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0006_fechareserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='numero_personas',
        ),
    ]
