# Generated by Django 4.0.4 on 2022-11-05 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0007_remove_reserva_numero_personas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='total',
        ),
    ]
