# Generated by Django 4.0.4 on 2022-11-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0008_remove_reserva_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='hora_salida',
            field=models.CharField(default='13:00', max_length=10, verbose_name='Hora de salida'),
        ),
    ]
