# Generated by Django 4.0.4 on 2022-11-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0009_alter_reserva_hora_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='numero_personas',
            field=models.CharField(default=2, max_length=2, verbose_name='numero de personas'),
            preserve_default=False,
        ),
    ]
