# Generated by Django 4.0.4 on 2022-11-02 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0002_habitacion_imagen_habitacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='imagen_habitacion',
        ),
    ]
