# Generated by Django 4.0.4 on 2022-11-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0003_remove_habitacion_imagen_habitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='capacidad',
            field=models.IntegerField(default=2, verbose_name='Capacidad'),
            preserve_default=False,
        ),
    ]
